# Generated by Django 4.1.7 on 2023-04-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("device_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="location",
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
